image: node:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test

deploy-npm:
  stage: deploy
  script:
    - npm install
    - npm run build
    - npm publish
  only:
    - /^release-.*$/
  when: manual
